import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { ThemeProvider } from "./components/theme-provider"
import { Toaster } from "./components/ui/toaster";
import { UserProvider } from "./components/Posts/UserContext";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, initialUser
}: Readonly<{
  children: React.ReactNode;
  initialUser:any;
}>) {
  return (
    <UserProvider initialUser={initialUser}>
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
          <Navbar />
          {children}
          <Toaster/>
        </ThemeProvider>
      </body>
    </html>
    </UserProvider>
  );
}
